services:
  flaskfarm-dev:
    build:
      context: .
      no_cache: true
    image: flaskfarm-dev
    container_name: flaskfarm-dev
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 10m
    volumes:
      - ${YOUR_FOLDER}/flaskfarm-dev:/flaskfarm-dev
      - ${YOUR_FOLDER}/projects:/projects
    environment:
      PUID: ${YOUR_PUID}
      PGID: ${YOUR_PGID}
      TZ: Asia/Seoul
